### PR TITLE
Update for Selenium 4.0.0

### PR DESCRIPTION
**Pull request by digitalcoyote**
Needed this for work. Let me know if there are any issues and I'll fix em.

Specifically Selenium 4.0.0 changed some interfaces and obsoleted a method.

### CODE REVIEW

**Comment by cezarypiatek** [comment]
Hi,
Thanks for your work. Two things to change:

1) Every operation that is proxied must be wrapped in `Execute( () =>)` otherwise it won't work as it's expected. For example:

```cs
    public ISearchContext GetShadowRoot() => Execute(()=> element.GetShadowRoot());
```

2) Can you amend the commit message to contain `BREAKING CHANGES` phrase? This will automatically bump up the package major version.

**Comment by digitalcoyote** [comment]
Absolutely, I'll try to get that in before work this morning.

**Comment by digitalcoyote** [comment]
I let Rider's Code completion do it with "Delegate implementation to element". I should have looked over it... I also corrected the formatting of the changes to match the rest of the file.

**Comment by cezarypiatek** [comment]
Excellent, thank you very much

**Pull request merged**
